"""add_metadata_and_auth_columns

Revision ID: 0281268d0d7f
Revises: 20260719_ai_analysis_full_response_additive
Create Date: 2026-07-19 21:09:39.286559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0281268d0d7f'
down_revision: Union[str, Sequence[str], None] = '20260719_ai_analysis_full_response_additive'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('status', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.add_column('logs', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('logs', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('mime', sa.String(length=255), nullable=True))
    op.add_column('logs', sa.Column('parser', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_logs_parser'), 'logs', ['parser'], unique=False)
    op.create_index(op.f('ix_logs_sha256'), 'logs', ['sha256'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_logs_sha256'), table_name='logs')
    op.drop_index(op.f('ix_logs_parser'), table_name='logs')
    op.drop_column('logs', 'parser')
    op.drop_column('logs', 'mime')
    op.drop_column('logs', 'size')
    op.drop_column('logs', 'sha256')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_column('alerts', 'status')
    # ### end Alembic commands ###
