"""initial

Revision ID: 03902652e31f
Revises: 
Create Date: 2026-07-19 17:54:16.198454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03902652e31f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Initial schema is created via Alembic by autogenerate.
    # Keep this migration explicit so environments can bootstrap.

    op.create_table(
        'users',
        sa.Column('id', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'logs',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('log_type', sa.String(length=100), nullable=False),
        sa.Column('source_filename', sa.String(length=500), nullable=True),
        sa.Column('uploaded_by_user_id', sa.String(length=36), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('total_events_estimated', sa.Integer(), nullable=True),
        sa.Column('total_alerts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('raw_text', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'log_events',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('log_id', sa.Integer(), sa.ForeignKey('logs.id'), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('source', sa.String(length=255), nullable=True),
        sa.Column('ip', sa.String(length=64), nullable=True),
        sa.Column('destination_ip', sa.String(length=64), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('process', sa.String(length=255), nullable=True),
        sa.Column('severity', sa.String(length=32), nullable=True),
        sa.Column('event_type', sa.String(length=64), nullable=False, server_default='unknown'),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('threat_score', sa.Float(), nullable=True),
        sa.Column('ioc_json', sa.Text(), nullable=True),
        sa.Column('raw_json', sa.Text(), nullable=True),
    )

    op.create_table(
        'incidents',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('log_id', sa.Integer(), sa.ForeignKey('logs.id'), nullable=False),
        sa.Column('incident_id', sa.String(length=64), nullable=False),
        sa.Column('log_type', sa.String(length=100), nullable=False),
        sa.Column('classification_type', sa.String(length=64), nullable=False),
        sa.Column('classification_description', sa.Text(), nullable=True),
        sa.Column('severity_level', sa.String(length=32), nullable=False),
        sa.Column('severity_score', sa.Integer(), nullable=True),
        sa.Column('confidence_value', sa.Integer(), nullable=True),
        sa.Column('confidence_rationale', sa.Text(), nullable=True),
        sa.Column('plain_english_attack_explanation', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'ai_analyses',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('log_id', sa.Integer(), sa.ForeignKey('logs.id'), nullable=False),
        sa.Column('incident_id', sa.Integer(), sa.ForeignKey('incidents.id'), nullable=True),
        sa.Column('model_name', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('confidence_value', sa.Float(), nullable=True),
        sa.Column('severity_level', sa.String(length=32), nullable=True),
        sa.Column('severity_score', sa.Integer(), nullable=True),
        sa.Column('classification_type', sa.String(length=64), nullable=True),
        sa.Column('raw_json', sa.Text(), nullable=True),
        # NOTE: updated_at + new fields added in later migrations.
    )

    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('log_id', sa.Integer(), sa.ForeignKey('logs.id'), nullable=False),
        sa.Column('incident_id', sa.Integer(), sa.ForeignKey('incidents.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('severity_level', sa.String(length=32), nullable=False),
        sa.Column('severity_score', sa.Integer(), nullable=True),
        sa.Column('threat_category', sa.String(length=64), nullable=True),
        sa.Column('confidence_value', sa.Float(), nullable=True),
    )

    op.create_table(
        'threats',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('log_id', sa.Integer(), sa.ForeignKey('logs.id'), nullable=False),
        sa.Column('incident_id', sa.Integer(), sa.ForeignKey('incidents.id'), nullable=True),
        sa.Column('threat_category', sa.String(length=64), nullable=False),
        sa.Column('confidence_value', sa.Float(), nullable=True),
        sa.Column('severity_level', sa.String(length=32), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'reports',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('incident_id', sa.Integer(), sa.ForeignKey('incidents.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('report_type', sa.String(length=64), nullable=False, server_default='dashboard'),
        sa.Column('content_json', sa.Text(), nullable=True),
    )

    op.create_table(
        'mitre_attack_mappings',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('alert_id', sa.Integer(), sa.ForeignKey('alerts.id'), nullable=True),
        sa.Column('incident_id', sa.Integer(), sa.ForeignKey('incidents.id'), nullable=True),
        sa.Column('technique_id', sa.String(length=32), nullable=False),
        sa.Column('technique_name', sa.String(length=255), nullable=True),
        sa.Column('tactics_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'iocs',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('alert_id', sa.Integer(), sa.ForeignKey('alerts.id'), nullable=True),
        sa.Column('incident_id', sa.Integer(), sa.ForeignKey('incidents.id'), nullable=True),
        sa.Column('ioc_value', sa.Text(), nullable=False),
        sa.Column('ioc_type', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('actor_user_id', sa.String(length=36), nullable=True),
        sa.Column('action', sa.String(length=128), nullable=False),
        sa.Column('details_json', sa.Text(), nullable=True),
    )

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop in reverse order.
    op.drop_table('audit_logs')
    op.drop_table('iocs')
    op.drop_table('mitre_attack_mappings')
    op.drop_table('reports')
    op.drop_table('threats')
    op.drop_table('alerts')
    op.drop_table('ai_analyses')
    op.drop_table('incidents')
    op.drop_table('log_events')
    op.drop_table('logs')
    op.drop_table('users')

    # ### end Alembic commands ###

